### ISSUE TITLE
SD-Card protection and volume settings

### ISSUE THREAD

**Issue by mjut** [kalanda/RPi-MediaLooper#1]
This project helped me out more than once. Nice!

In the readme it is described "Prevent SD card from getting corrupted" - but I can not get this to work. By following these steps, my Pi won'd start up anymore.

Another thing: is it possible to set the volume? Maybe in the config.txt?

Thanks!!

**Comment by kalanda** [comment]
Thanks @mjut, glad to be helpful. 

About the "Prevent SD card from getting corrupted", this is where I got the information meanwhile I was preparing the project.
https://raspberrypi.stackexchange.com/questions/7978/how-can-i-prevent-my-pis-sd-card-from-getting-corrupted-so-often?answertab=active#tab-top

About the audio volume, I can't help you at this moment but should be easy to control in some way:
http://blog.scphillips.com/posts/2013/01/sound-configuration-on-raspberry-pi-with-alsa/

**Comment by mjut** [comment]
Cool! Many thanks @kalanda =)
I ll look into this now.
